name: Build Windows

on:
  workflow_dispatch:

jobs:
  call-flutter-build:
    uses: ./.github/workflows/flutter-build1.yml
    with:
      upload-artifact: true
      upload-tag: "master"
    secrets: inherit
